// This file was auto-generated by prisma-generator-typescript-interfaces

type role = "Admin" | "User";

type article_category = "Nasional" | "Internasional" | "Politik" | "Ekonomi_Bisnis" | "Teknologi" | "Olahraga" | "Hiburan" | "Gaya_Hidup" | "Kesehatan" | "Edukasi" | "Sains" | "Lingkungan" | "Hukum_Kriminal" | "Human_Interest" | "Opini_Editorial" | "Properti_Real_Estate" | "Transportasi" | "Pariwisata" | "Kuliner" | "Keuangan_Pribadi" | "Agama_Spiritualitas" | "Psikologi_Pengembangan_Diri" | "Komunitas_Sosial" | "Sejarah" | "Budaya_Pop" | "Ekonomi_Kreatif" | "Ekologi_Keanekaragaman_Hayati";

interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  phone_number: string;
  role: role;
  comment?: Comment[];
  article?: Article[];
}

interface Article {
  id: number;
  user_id: number;
  title: string;
  description: string;
  like: number;
  comment_count: number;
  created_at: Date;
  category: article_category | null;
  topic: string | null;
  writter: string | null;
  tags: string[];
  comment?: Comment[];
  user?: User;
}

interface Comment {
  id: string;
  article_id: number;
  user_id: number;
  comment: string;
  created_at: Date;
  article?: Article;
  user?: User;
}

export type { User, Article, Comment, role, article_category };