// This file was auto-generated by prisma-generator-typescript-interfaces

export type Role = "Admin" | "User";

export type Article_Category = "Nasional" | "Internasional" | "Politik" | "Ekonomi_Bisnis" | "Teknologi" | "Olahraga" | "Hiburan" | "Gaya_Hidup" | "Kesehatan" | "Edukasi" | "Sains" | "Lingkungan" | "Hukum_Kriminal" | "Human_Interest" | "Opini_Editorial" | "Properti_Real_Estate" | "Transportasi" | "Pariwisata" | "Kuliner" | "Keuangan_Pribadi" | "Agama_Spiritualitas" | "Psikologi_Pengembangan_Diri" | "Komunitas_Sosial" | "Sejarah" | "Budaya_Pop" | "Ekonomi_Kreatif" | "Ekologi_Keanekaragaman_Hayati";

export const articleCategory: Article_Category[] = [
  "Nasional", 
  "Internasional", 
  "Politik", 
  "Ekonomi_Bisnis", 
  "Teknologi", 
  "Olahraga", 
  "Hiburan", 
  "Gaya_Hidup", 
  "Kesehatan", 
  "Edukasi", 
  "Sains", 
  "Lingkungan", 
  "Hukum_Kriminal", 
  "Human_Interest", 
  "Opini_Editorial", 
  "Properti_Real_Estate", 
  "Transportasi", 
  "Pariwisata", 
  "Kuliner", 
  "Keuangan_Pribadi", 
  "Agama_Spiritualitas", 
  "Psikologi_Pengembangan_Diri", 
  "Komunitas_Sosial", 
  "Sejarah", 
  "Budaya_Pop", 
  "Ekonomi_Kreatif", 
  "Ekologi_Keanekaragaman_Hayati"
];

export interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  phone_number: string;
  role: Role;
  article?: Article[];
  comment?: Comment[];
  like?: Like[];
  created_at: Date;
}

export interface Article {
  id: number;
  user_id: number;
  user?: User;
  title: string;
  description: string;
  category: Article_Category | null;
  topic: string | null;
  writter: string | null;
  image: string | null;
  tags: string[];
  liked_by?: Like[];
  like_count: number;
  comment?: Comment[];
  comment_count: number;
  created_at: Date;
}

export interface Comment {
  id: string;
  article_id: number;
  user_id: number;
  comment: string;
  created_at: Date;
  article?: Article;
  user?: User;
}

export interface Like {
  user?: User;
  user_id: number;
  article?: Article;
  article_id: number;
  liked_at: Date;
}
